-- Migration 032: Switch every UUID primary-key DEFAULT from gen_random_uuid()
-- to uuidv7().
--
-- Every id in this schema is generated by types.NewID(), which has produced a
-- version 7 UUID since it was written: v7 puts a 48-bit timestamp in the high
-- bits, so successive ids sort in insertion order and land next to each other
-- in an index instead of scattering across it. The column DEFAULTs never got
-- the same treatment. gen_random_uuid() is DuckDB's v4 generator -- confirmed
-- with uuid_extract_version(gen_random_uuid()), which returns 4 -- so the
-- schema's fallback contradicts the application's rule.
--
-- Nothing generates a v4 id today. Every repository INSERT names id in its
-- column list and passes the value from Go, so the DEFAULT is unreachable on
-- every current code path. This migration closes a latent gap rather than
-- fixing live behavior: it means a future INSERT that omits id, or a hand-
-- written statement against the file, gets a v7 id instead of quietly
-- introducing the one v4 in a table full of v7s.
--
-- Existing rows are untouched. A DEFAULT applies only to future inserts, so
-- no id changes and no index is rewritten.
--
-- uuidv7() has been a DuckDB built-in since 1.3.0; this project builds against
-- the 1.5.x bindings in duckdb-go/v2.

ALTER TABLE accounts ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE categories ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE corporate_actions ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE investment_lots ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE investment_positions ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE investment_transaction_lots ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE investment_transactions ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE payee_aliases ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE payees ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE reconciliation_sessions ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE scheduled_split_items ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE scheduled_transactions ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE securities ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE security_prices ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE transaction_splits ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE transactions ALTER COLUMN id SET DEFAULT uuidv7();
